### ISSUE TITLE
EOV page 

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/BioOceanObserver#196]
Organise to split the plots when printed, or to choose which plots to print.

Jan and Dec missing from axes.

**Comment by jaseeverett** [comment]
This page is quite slow to render due to the number of plots and hard to print because there are so many plots to fit onto a small page. I am going to propose 3 options for improving this:

1. We provide a list of EOVs that can be chosen (tickboxes) and the user selects the ones they want up to a maximum number.
2. We create tabs for each set of EOVs - Biological (Biomass + Diversity), Physical, BioChemical. (But this means users can put physical and biological next to each other)
3.  We have a combination of 1 + 2. We provide an "All tab" which allows up to 5 (?) EOVs to be chosen Then we have 3 other tabs were you can see them (no selection allowed) in the categories above. 

My preference 3). What do you think @clairedavies

**Comment by clairedavies** [comment]
3

**Comment by jaseeverett** [comment]
Completed with #217
